# Generated by Django 4.0.6 on 2022-07-08 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ease', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fmmodel',
            name='acoustic_panel_comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='fmmodel',
            name='aviation_obstruction_light_comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='fmmodel',
            name='backup_power_comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='fmmodel',
            name='cavity_filter_comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='fmmodel',
            name='comments_remarks',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='fmmodel',
            name='directional_antenna_comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='fmmodel',
            name='epa_permit_comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='fmmodel',
            name='equipment_sheet_comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='fmmodel',
            name='fire_permit_comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='fmmodel',
            name='lighting_arrestor_comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='fmmodel',
            name='mast_earthed_comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='fmmodel',
            name='mast_right_colors_comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='fmmodel',
            name='on_air_lighting_comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='fmmodel',
            name='reception_comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='fmmodel',
            name='secure_door_comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='fmmodel',
            name='security_post_comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='fmmodel',
            name='signage_board_comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='fmmodel',
            name='ventillation_equipment_comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='tvmodel',
            name='acoustic_panel_comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='tvmodel',
            name='aviation_obstruction_light_comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='tvmodel',
            name='backup_power_comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='tvmodel',
            name='comments_remarks',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='tvmodel',
            name='epa_permit_comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='tvmodel',
            name='equipment_sheet_comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='tvmodel',
            name='fire_permit_comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='tvmodel',
            name='lighting_arrestor_comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='tvmodel',
            name='mast_earthed_comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='tvmodel',
            name='mast_right_colors_comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='tvmodel',
            name='on_air_lighting_comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='tvmodel',
            name='reception_comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='tvmodel',
            name='satellite_provider_comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='tvmodel',
            name='secure_door_comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='tvmodel',
            name='security_post_comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='tvmodel',
            name='signage_board_comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='tvmodel',
            name='ventillation_equipment_comment',
            field=models.TextField(blank=True, default=''),
        ),
    ]
