# Generated by Django 4.0.6 on 2022-07-08 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ease', '0002_alter_fmmodel_acoustic_panel_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fmmodel',
            name='antenna_gain',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='fmmodel',
            name='mast_height',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='fmmodel',
            name='operating_frequency',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='tvmodel',
            name='antenna_gain',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='tvmodel',
            name='mast_height',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='tvmodel',
            name='operating_frequency',
            field=models.FloatField(default=0.0),
        ),
    ]
