# Generated by Django 4.0.6 on 2022-07-09 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ease', '0004_notificationmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationmodel',
            name='seen',
            field=models.BooleanField(default=False),
        ),
    ]
