# Generated by Django 4.0.6 on 2022-07-09 07:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ease', '0005_notificationmodel_seen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationmodel',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
