# Generated by Django 4.0.6 on 2022-07-09 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ease', '0006_alter_notificationmodel_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fmmodel',
            name='ventillation_equipment_comment',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
